# Basic
title: Godfrey Johnson
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/GodfreyJohnson/GodfreyJohnson.github.io" target="_blank">Welcome</a>
description: We Sing. We Dance. We Steal Things.
creator: <a>@GodfreyJohnson</a>

#url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: godfreyjohnson
